### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by aleksasiriski** [Shadowghost/jellyfin-rffmpeg#4]
Doesn't work, I guess because rffmpeg expects jellyfin process to be running as jellyfin user but the official jellyfin docker, from which this is built, runs jellyfin as root?

**Comment by aleksasiriski** [comment]
By doesn't work I meant, jellyfin works normally but when I try to run `docker exec -it jellyfin rffmpeg init` I get this:

```Are you sure you want to (re)initalize the database [y/N]? y
Initializing database
Traceback (most recent call last):
  File "/usr/local/bin/rffmpeg", line 782, in <module>
    run_control(config)
  File "/usr/local/bin/rffmpeg", line 770, in run_control
    return rffmpeg_click(obj={})
  File "/usr/lib/python3/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/bin/rffmpeg", line 552, in rffmpeg_click_init
    getpwnam(config["dir_owner"]).pw_uid,
KeyError: "getpwnam(): name not found: 'jellyfin'"```

**Comment by Sim0nW0lf** [comment]
> Doesn't work, I guess because rffmpeg expects jellyfin process to be running as jellyfin user but the official jellyfin docker, from which this is built, runs jellyfin as root?

You can change the user it should run as in the `/etc/rffmpeg/rffmpeg.yml` config file.

See the documentation here: https://github.com/joshuaboniface/rffmpeg/blob/883d4333685af606af1685264f1b481fc2635951/rffmpeg.yml.sample#L43

**Comment by Shadowghost** [comment]
I haven't tested this with recent versions of rffmpeg since I don't use it myself anymore.

Try creating the yml manually.

**Comment by aleksasiriski** [comment]
It has nothing to do about ssh connection, rffmpeg can't initialize itself because it's running as root but expects to be running as jellyfin user.

```
podman create --name=jellyfin --user jellyfin:jellyfin -p 8096:8096 -v jellyfin-conf:/config:Z -v rffmpeg-conf:/etc/rffmpeg:Z -v jellyfin-data:/data:Z bitwrk/jellyfin-rffmpeg
be94696d8daf421b06e8baf0579e2d28d0fffa03362f36da2432a541419d8630
aleksa@workstation ~> podman start jellyfin
Error: unable to start container "be94696d8daf421b06e8baf0579e2d28d0fffa03362f36da2432a541419d8630": unable to find user jellyfin: no matching entries in passwd file
```





```
aleksa@workstation ~> podman create --name=jellyfin --user 1000:1000 -p 8096:8096 -v jellyfin-conf:/config:Z -v rffmpeg-conf:/etc/rffmpeg:Z -v jellyfin-data:/data:Z bitwrk/jellyfin-rffmpeg
7c16882906a4df368f6073ef24dd86859ca6534ee3613a0a11ec6c01870c5beb
aleksa@workstation ~> podman start jellyfin
jellyfin
aleksa@workstation ~> podman exec -it jellyfin rffmpeg init
Error: This command requires root privileges.
```





```
aleksa@workstation ~> podman create --name=jellyfin -p 8096:8096 -v jellyfin-conf:/config:Z -v rffmpeg-conf:/etc/rffmpeg:Z -v jellyfin-data:/data:Z bitwrk/jellyfin-rffmpeg
c49b3a7915a9052bc125dd4344d76df36e59c1b7b2b4828412cb41b8a26e5e86
aleksa@workstation ~> podman start jellyfin
jellyfin
aleksa@workstation ~> podman exec -it jellyfin rffmpeg init
Are you sure you want to (re)initalize the database [y/N]? y
Initializing database
Traceback (most recent call last):
  File "/usr/local/bin/rffmpeg", line 782, in <module>
    run_control(config)
  File "/usr/local/bin/rffmpeg", line 770, in run_control
    return rffmpeg_click(obj={})
  File "/usr/lib/python3/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/bin/rffmpeg", line 552, in rffmpeg_click_init
    getpwnam(config["dir_owner"]).pw_uid,
KeyError: "getpwnam(): name not found: 'jellyfin'"
```

**Comment by Sim0nW0lf** [comment]
I fixed it in the Dockerfile...
Just build it again with the new Dockerfile and it will work.

**Comment by aleksasiriski** [comment]
Ok, thanks!

**Comment by Sim0nW0lf** [comment]
> It has nothing to do about ssh connection, rffmpeg can't initialize itself because it's running as root but expects to be running as jellyfin user.
> 
> ```
> podman create --name=jellyfin --user jellyfin:jellyfin -p 8096:8096 -v jellyfin-conf:/config:Z -v rffmpeg-conf:/etc/rffmpeg:Z -v jellyfin-data:/data:Z bitwrk/jellyfin-rffmpeg
> be94696d8daf421b06e8baf0579e2d28d0fffa03362f36da2432a541419d8630
> aleksa@workstation ~> podman start jellyfin
> Error: unable to start container "be94696d8daf421b06e8baf0579e2d28d0fffa03362f36da2432a541419d8630": unable to find user jellyfin: no matching entries in passwd file
> ```
> 
> ```
> aleksa@workstation ~> podman create --name=jellyfin --user 1000:1000 -p 8096:8096 -v jellyfin-conf:/config:Z -v rffmpeg-conf:/etc/rffmpeg:Z -v jellyfin-data:/data:Z bitwrk/jellyfin-rffmpeg
> 7c16882906a4df368f6073ef24dd86859ca6534ee3613a0a11ec6c01870c5beb
> aleksa@workstation ~> podman start jellyfin
> jellyfin
> aleksa@workstation ~> podman exec -it jellyfin rffmpeg init
> Error: This command requires root privileges.
> ```
> 
> ```
> aleksa@workstation ~> podman create --name=jellyfin -p 8096:8096 -v jellyfin-conf:/config:Z -v rffmpeg-conf:/etc/rffmpeg:Z -v jellyfin-data:/data:Z bitwrk/jellyfin-rffmpeg
> c49b3a7915a9052bc125dd4344d76df36e59c1b7b2b4828412cb41b8a26e5e86
> aleksa@workstation ~> podman start jellyfin
> jellyfin
> aleksa@workstation ~> podman exec -it jellyfin rffmpeg init
> Are you sure you want to (re)initalize the database [y/N]? y
> Initializing database
> Traceback (most recent call last):
>   File "/usr/local/bin/rffmpeg", line 782, in <module>
>     run_control(config)
>   File "/usr/local/bin/rffmpeg", line 770, in run_control
>     return rffmpeg_click(obj={})
>   File "/usr/lib/python3/dist-packages/click/core.py", line 829, in __call__
>     return self.main(*args, **kwargs)
>   File "/usr/lib/python3/dist-packages/click/core.py", line 782, in main
>     rv = self.invoke(ctx)
>   File "/usr/lib/python3/dist-packages/click/core.py", line 1259, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/usr/lib/python3/dist-packages/click/core.py", line 610, in invoke
>     return callback(*args, **kwargs)
>   File "/usr/local/bin/rffmpeg", line 552, in rffmpeg_click_init
>     getpwnam(config["dir_owner"]).pw_uid,
> KeyError: "getpwnam(): name not found: 'jellyfin'"
> ```

Sorry, before I linked it wrong!
This is the correct line: https://github.com/joshuaboniface/rffmpeg/blob/883d4333685af606af1685264f1b481fc2635951/rffmpeg.yml.sample#L33

**Comment by aleksasiriski** [comment]
The python program `rffmpeg` had hardcoded the user jellyfin should be running as and since official jellyfin container doesn't use `jellyfin` but plain `root` and `--user uid:gid` as optional user that still didn't work.

https://raw.githubusercontent.com/joshuaboniface/rffmpeg/master/rffmpeg
Line 116: ```config["dir_owner"] = config_directories.get("owner", "jellyfin")```

I made this Dockerfile with the fix, I haven't tested if this works yet but at least I don't get errors when docker exec-ing `rffmpeg init` anymore...

```
FROM ghcr.io/confusedpolarbear/jellyfin-intro-skipper

RUN apt update && \
    apt install -y openssh-client python3-click python3-yaml wget

RUN mkdir -p /usr/lib/rffmpeg && \
    wget https://raw.githubusercontent.com/joshuaboniface/rffmpeg/master/rffmpeg -O /usr/local/bin/rffmpeg && \
    sed -i 's;("owner", "jellyfin");("owner", "root");' /usr/local/bin/rffmpeg && \
    sed -i 's;("group", "sudo");("group", "root");' /usr/local/bin/rffmpeg && \
    chmod +x /usr/local/bin/rffmpeg && \
    ln -s /usr/local/bin/rffmpeg /usr/local/bin/ffmpeg && \
    ln -s /usr/local/bin/rffmpeg /usr/local/bin/ffprobe

RUN mkdir -p /etc/rffmpeg && \
    wget https://raw.githubusercontent.com/joshuaboniface/rffmpeg/master/rffmpeg.yml.sample -O /etc/rffmpeg/rffmpeg.yml && \
    sed -i 's;#persist: "/run/shm";persist: "/run";' /etc/rffmpeg/rffmpeg.yml && \
    sed -i 's;#state: "/var/lib/rffmpeg";state: "/config/rffmpeg";' /etc/rffmpeg/rffmpeg.yml && \
    sed -i 's;#owner: jellyfin;owner: root;' /etc/rffmpeg/rffmpeg.yml && \
    sed -i 's;#group: sudo;group: root;' /etc/rffmpeg/rffmpeg.yml

RUN apt purge wget -y && \
    rm -rf /var/lib/apt/lists/* && \
    apt autoremove --purge -y && \
    apt clean

ENTRYPOINT "./jellyfin/jellyfin"
```

**Comment by aleksasiriski** [comment]
Now I can't set the rffmpeg location as ffmpeg, getting error message from jellyfin:

```
We're unable to find FFmpeg using the path you've entered. FFprobe is also required and must exist in the same folder. These components are normally bundled together in the same download. Please check the path and try again.
```

**Comment by Sim0nW0lf** [comment]
What path are you using in the Jellyfin settings?

I am using this path: `/usr/local/bin/ffmpeg`

**Comment by aleksasiriski** [comment]
![image](https://user-images.githubusercontent.com/31509435/197888364-1235c30f-70e1-4a14-a058-4bfe117f9ecc.png)
![image](https://user-images.githubusercontent.com/31509435/197888382-e01b8583-3577-4a7c-835a-4d6065c66b85.png)

**Comment by aleksasiriski** [comment]
![image](https://user-images.githubusercontent.com/31509435/197888463-de22bbb6-1a51-49c9-89a3-2016cf13e844.png)

**Comment by Sim0nW0lf** [comment]
I do remember having the same problem at some point!
Not sure how I fixed it 🤔 But I tried changing paths, restarting/reinstalling. Somehow it worked in the end...

Let me setup a test to see if I can replicate this again.

**Comment by aleksasiriski** [comment]
It's probably related to this, I guess rffmpeg doesn't return a new enough version of ffmpeg.
https://github.com/jellyfin/jellyfin/issues/5673

**Comment by aleksasiriski** [comment]
Could you try my Dockerfile to see if it works for you? I'm testing on Fedora Silverblue using podman version 4.2.1
```
FROM ghcr.io/confusedpolarbear/jellyfin-intro-skipper

RUN apt update && \
    apt install -y openssh-client python3-click python3-yaml wget

RUN mkdir -p /usr/lib/rffmpeg && \
    wget https://raw.githubusercontent.com/joshuaboniface/rffmpeg/master/rffmpeg -O /usr/local/bin/rffmpeg && \
    sed -i 's;"/var/log/jellyfin/rffmpeg.log";"/config/log/rffmpeg.log";' /usr/local/bin/rffmpeg && \
    sed -i 's;("owner", "jellyfin");("owner", "root");' /usr/local/bin/rffmpeg && \
    sed -i 's;("group", "sudo");("group", "root");' /usr/local/bin/rffmpeg && \
    chmod +x /usr/local/bin/rffmpeg && \
    ln -s /usr/local/bin/rffmpeg /usr/local/bin/ffmpeg && \
    ln -s /usr/local/bin/rffmpeg /usr/local/bin/ffprobe

RUN mkdir -p /etc/rffmpeg && \
    wget https://raw.githubusercontent.com/joshuaboniface/rffmpeg/master/rffmpeg.yml.sample -O /etc/rffmpeg/rffmpeg.yml && \
    sed -i 's;#persist: "/run/shm";persist: "/run";' /etc/rffmpeg/rffmpeg.yml && \
    sed -i 's;#state: "/var/lib/rffmpeg";state: "/config/rffmpeg";' /etc/rffmpeg/rffmpeg.yml && \
    sed -i 's;#owner: jellyfin;owner: root;' /etc/rffmpeg/rffmpeg.yml && \
    sed -i 's;#group: sudo;group: root;' /etc/rffmpeg/rffmpeg.yml

RUN apt purge wget -y && \
    rm -rf /var/lib/apt/lists/* && \
    apt autoremove --purge -y && \
    apt clean

ENTRYPOINT ["./jellyfin/jellyfin", \
    "--datadir", "/config", \
    "--cachedir", "/cache", \
    "--ffmpeg", "/usr/local/bin/ffmpeg"]
```

`docker exec -it jellyfin rffmpeg init`
or
`podman exec -it jellyfin rffmpeg init`

**Comment by aleksasiriski** [comment]
ok it started working now, literally just changed the entrypoint and after removing volumes it still didn't work but now after clean start of the container ONLY AFTER initializing rffmpeg with `rffmpeg init` it works... amazing

**Comment by aleksasiriski** [comment]
I'm going to test it now with some media and a remote host...

**Comment by Sim0nW0lf** [comment]
Hmmm, fallback to localhost should happen by default but yeah a clean reinstall fixed it for me too at some point I guess.
If your hosts run without docker you just have to make sure jellyfin-ffmpeg5 is being used, not jellyfin-ffmpeg!
Also don't forget to mount your media, /config, /data and /cache from the docker server to your hosts 😁

Happy for you that it worked now and I hope the rest will work flawlessly! 👌🏼

**Comment by aleksasiriski** [comment]
https://github.com/aleksasiriski/jellyfin-intro-skipper-rffmpeg

ghcr.io/aleksasiriski/jellyfin-intro-skipper-rffmpeg

**Comment by Sim0nW0lf** [comment]
> Could you try my Dockerfile to see if it works for you? I'm testing on Fedora Silverblue using podman version 4.2.1
> 
> ```
> FROM ghcr.io/confusedpolarbear/jellyfin-intro-skipper
> 
> RUN apt update && \
>     apt install -y openssh-client python3-click python3-yaml wget
> 
> RUN mkdir -p /usr/lib/rffmpeg && \
>     wget https://raw.githubusercontent.com/joshuaboniface/rffmpeg/master/rffmpeg -O /usr/local/bin/rffmpeg && \
>     sed -i 's;"/var/log/jellyfin/rffmpeg.log";"/config/log/rffmpeg.log";' /usr/local/bin/rffmpeg && \
>     sed -i 's;("owner", "jellyfin");("owner", "root");' /usr/local/bin/rffmpeg && \
>     sed -i 's;("group", "sudo");("group", "root");' /usr/local/bin/rffmpeg && \
>     chmod +x /usr/local/bin/rffmpeg && \
>     ln -s /usr/local/bin/rffmpeg /usr/local/bin/ffmpeg && \
>     ln -s /usr/local/bin/rffmpeg /usr/local/bin/ffprobe
> 
> RUN mkdir -p /etc/rffmpeg && \
>     wget https://raw.githubusercontent.com/joshuaboniface/rffmpeg/master/rffmpeg.yml.sample -O /etc/rffmpeg/rffmpeg.yml && \
>     sed -i 's;#persist: "/run/shm";persist: "/run";' /etc/rffmpeg/rffmpeg.yml && \
>     sed -i 's;#state: "/var/lib/rffmpeg";state: "/config/rffmpeg";' /etc/rffmpeg/rffmpeg.yml && \
>     sed -i 's;#owner: jellyfin;owner: root;' /etc/rffmpeg/rffmpeg.yml && \
>     sed -i 's;#group: sudo;group: root;' /etc/rffmpeg/rffmpeg.yml
> 
> RUN apt purge wget -y && \
>     rm -rf /var/lib/apt/lists/* && \
>     apt autoremove --purge -y && \
>     apt clean
> 
> ENTRYPOINT ["./jellyfin/jellyfin", \
>     "--datadir", "/config", \
>     "--cachedir", "/cache", \
>     "--ffmpeg", "/usr/local/bin/ffmpeg"]
> ```
> 
> `docker exec -it jellyfin rffmpeg init` or `podman exec -it jellyfin rffmpeg init`

These changes here are not necessary.
>```
>     sed -i 's;"/var/log/jellyfin/rffmpeg.log";"/config/log/rffmpeg.log";' /usr/local/bin/rffmpeg && \
>     sed -i 's;("owner", "jellyfin");("owner", "root");' /usr/local/bin/rffmpeg && \
>     sed -i 's;("group", "sudo");("group", "root");' /usr/local/bin/rffmpeg && \
>```
As you can read [here](https://www.w3schools.com/python/ref_dictionary_get.asp) these values are not hardcoded but a fallback if the values are not set in the config file.
You should instead make sure that your config file is indeed being loaded and change all values there like you also do in this Dockerfile. Just also add a new path for your logs if you want to change the directory.
```
     sed -i 's;#logfile: "/var/log/jellyfin/rffmpeg.log";logfile: "/config/log/rffmpeg.log";' /etc/rffmpeg/rffmpeg.yml && \
     sed -i 's;#persist: "/run/shm";persist: "/run";' /etc/rffmpeg/rffmpeg.yml && \
     sed -i 's;#state: "/var/lib/rffmpeg";state: "/config/rffmpeg";' /etc/rffmpeg/rffmpeg.yml && \
     sed -i 's;#owner: jellyfin;owner: root;' /etc/rffmpeg/rffmpeg.yml && \
     sed -i 's;#group: sudo;group: root;' /etc/rffmpeg/rffmpeg.yml
```

**Comment by aleksasiriski** [comment]
Thanks for all your help, if you want you can check out my updated repo and image (same url).

Also I made my own node as this one is outdated and not working for me: https://github.com/BasixKOR/rffmpeg-docker

https://github.com/aleksasiriski/jellyfin-rffmpeg-node
ghcr.io/aleksasiriski/jellyfin-rffmpeg-node
