### ISSUE TITLE
Updating Jellyfin Base Image

### ISSUE THREAD

**Issue by felixjulianheitmann** [Shadowghost/jellyfin-rffmpeg#7]
Hi, on here https://hub.docker.com/r/bitwrk/jellyfin-rffmpeg you are writing the unstable images are built every 30 minutes.

Would you consider an automation for the stable builds as well? They are currently quite a bit out of date: v10.8.5 vs. v10.10.3

Something like every couple of days would already be sufficient to get this image up to date. I wanted to try this by drop-in replacing my jellyfin container with it and it crashed because of db schema migrations.

**Comment by Shadowghost** [comment]
Hey, usually I'm just doing them manually. But I don't use rffmpeg myself anymore, so I keep forgetting about it.
Pushed updates for all stable versions.

**Comment by felixjulianheitmann** [comment]
Nice stuff, I'll try it today. Why did you stop using it, if I may ask? Did you stop using jellyfin altogether or do you encode locally now?

**Comment by Shadowghost** [comment]
Local encoding
